# Site settings
title: Go Web Scraper
description: A comprehensive web scraping solution built in Go with database integration and web interface
baseurl: "/go-web-scraper"
url: "https://goecosystem.github.io"
repository: GoEcosystem/go-web-scraper
last_updated: "2025-04-05"

# Build settings
markdown: kramdown
highlighter: rouge

# Jekyll settings
permalink: pretty

# GitHub Pages settings
github:
  is_project_page: true
  repository_url: https://github.com/GoEcosystem/go-web-scraper
  repository_name: go-web-scraper
  owner_name: GoEcosystem
  owner_url: https://github.com/GoEcosystem

# Theme and plugins
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-github-metadata

# Link rendering
relative_links:
  enabled: true
  collections: true

# Default layouts
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "api"
    values:
      layout: "api"
  - scope:
      path: "guides"
    values:
      layout: "guide"
  - scope:
      path: "reference"
    values:
      layout: "reference"

# Exclude from processing
exclude:
  - .git/
  - .github/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Navigation
navigation:
  - title: Home
    url: /
  - title: API Reference
    url: /api/
  - title: Architecture
    url: /architecture/
  - title: GoEcosystem
    url: https://goecosystem.github.io

# GitHub Pages specific settings
lsi: false
safe: true
source: .
incremental: false
gist:
  noscript: false

# GitHub
github:
  repository_url: https://github.com/GoEcosystem/go-web-scraper
  zip_url: https://github.com/GoEcosystem/go-web-scraper/archive/refs/heads/main.zip
  tar_url: https://github.com/GoEcosystem/go-web-scraper/archive/refs/heads/main.tar.gz
